-- CREATE DATABASE, IF IT DOES NOT EXIST
CREATE DATABASE IF NOT EXISTS mcsp02donuts;

-- CONNECT TO THE DATABASE
USE mcsp02donuts;

-- CREATE DONUTS TABLE
-- WITH COLUMNS
CREATE TABLE IF NOT EXISTS donuts(
    id integer AUTO_INCREMENT UNIQUE KEY PRIMARY KEY,
    filling VARCHAR(25),
    stale TINYINT(1)
    );

